# ============================================================
# &l&6WeatherControl Plugin
# &r&7Description: &fУправление погодой и временем на сервере.
# &r&7Developed by: &fReStudios
# ============================================================

messages:
  no_permission: "&c&lУ вас нет прав на выполнение этой команды."
  config_reloaded: "&a&lКонфигурация плагина WeatherControl успешно перезагружена."
  sunny: "&6&lПогода изменена на &eсолнечную!"
  rain: "&6&lПогода изменена на &eдождливую!"
  thunder: "&6&lПогода изменена на &eгрозу!"
  day: "&6&lВремя установлено на &eдень."
  night: "&6&lВремя установлено на &eночь."
  weather_usage: "&c&lИспользуйте: /weather <sunny|rain|thunder>"
  time_usage: "&c&lИспользуйте: /timecontrol <day|night>"
  vote_usage: "&c&lИспользуйте: /voteweather или /votetime"
  vote_start_weather: "&6&lНачалось голосование за погоду! Нажмите на кнопки ниже, чтобы проголосовать:"
  vote_start_time: "&6&lНачалось голосование за смену времени суток! Нажмите на кнопки ниже, чтобы проголосовать:"
  vote: "&6&lГолосования:"
  vote_active: "&c&lГолосование уже активно."
  vote_inactive: "&c&lВ данный момент нет активных голосований."
  vote_success: "&2&lГолосовать за"
  vote_invalid: "&4&lГолосовать против"
  invalid_command: "&c&lНеверная команда."
  invalid_vote: "&c&lНеверный вариант голоса. Используйте 'yes' или 'no'."
  invalid_vote_type: "&c&lНеверный тип голосования. Используйте 'weather' или 'time'."
  vote_accepted: "&a&lВаш голос принят."
  vote_rejected: "&c&lГолосование за смену погоды отклонено."
  time_vote_rejected: "&c&lГолосование за смену времени суток отклонено."
  help_menu:
    - "&6======&e&lWeatherControl&6======"
    - "&6/voteweather - &eНачать голосование за изменение погоды."
    - "&6/votetime - &eНачать голосование за изменение времени суток."
    - "&6/castvote <weather/time> <yes/no> - &eПроголосовать за изменение погоды или времени суток."
    - "&6/weather <sunny/rain/thunder> - &eИзменить погоду вручную."
    - "&6/time <day/night> - &eИзменить время суток вручную."
    - "&6/weathercontrolreload - &eПерезагрузить конфигурацию плагина."
    - "&6=====Разработано by &2&lReStudios&6====="

weather:
  auto_change_interval: 600  # Интервал смены погоды в секундах

vote_duration: 30  # Длительность голосования в секундах
